- name: Create EC2 Instance
  amazon.aws.ec2_instance:
    name: "kafka-demo-server"
    key_name: "chris-aws"
    vpc_subnet_id: subnet-0ba9958ce9570c5f3
    instance_type: t2.medium
    security_group: kafka
    region: eu-west-2
    image_id: ami-0f9535ac605dc21d5
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 50
          delete_on_termination: true
    tags:
      Environment: Demo
